// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQQFqHDbYaNxXtveTHMHenyoUArLWyH_k',
    appId: '1:468325232636:web:e1f05a67e9984a4e730c79',
    messagingSenderId: '468325232636',
    projectId: 'framework-7ac99',
    authDomain: 'framework-7ac99.firebaseapp.com',
    storageBucket: 'framework-7ac99.firebasestorage.app',
    measurementId: 'G-5Q62X3L2ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB9JcQJAGrpsfMlq3C1mUVFlvlP4t6iUo',
    appId: '1:468325232636:android:46664eabeb7cf417730c79',
    messagingSenderId: '468325232636',
    projectId: 'framework-7ac99',
    storageBucket: 'framework-7ac99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK40VBXqZnb6f7EcLR6b_MDvB152DGlqM',
    appId: '1:468325232636:ios:6630be4f68d6c293730c79',
    messagingSenderId: '468325232636',
    projectId: 'framework-7ac99',
    storageBucket: 'framework-7ac99.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorPalestras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK40VBXqZnb6f7EcLR6b_MDvB152DGlqM',
    appId: '1:468325232636:ios:6630be4f68d6c293730c79',
    messagingSenderId: '468325232636',
    projectId: 'framework-7ac99',
    storageBucket: 'framework-7ac99.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorPalestras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQQFqHDbYaNxXtveTHMHenyoUArLWyH_k',
    appId: '1:468325232636:web:59eebe4e86280754730c79',
    messagingSenderId: '468325232636',
    projectId: 'framework-7ac99',
    authDomain: 'framework-7ac99.firebaseapp.com',
    storageBucket: 'framework-7ac99.firebasestorage.app',
    measurementId: 'G-CZLH6KXJN7',
  );
}
